name: release

on:
  workflow_dispatch:
    inputs:
      bump_type:
        required: true
        default: 'patch'
        type: choice
        options:
          - major
          - minor
          - patch

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
          registry-url: 'https://registry.npmjs.org'

      - name: Setup Git
        run: |
          git config user.name "Midra"
          git config user.email "me@midra.me"

      - name: Set AuthToken for npmjs.com
        run: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > "${HOME}/.npmrc"
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Update package version
        run: |
          pnpm version ${{ github.event.inputs.bump_type }}
          echo VERSION="v$(cat package.json | jq -r '.version')" >> "${GITHUB_ENV}"

      - name: Publish to npmjs
        run: |
          pnpm install
          pnpm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Push tag to GitHub
        run: |
          git push
          git push --tags

      - name: Create Release to GitHub
        run: |
          gh release create "${VERSION}" --generate-notes
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
